name: "Meeting"
on:
  issue_comment:
    types: [created, edited]
jobs:
  meeting:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        # 0 indicates all history
        fetch-depth: 0
    - uses: pkgjs/meet@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-10-09T18:15:11+0000/P1D
