name: "Meeting"
on: workflow_dispatch
jobs:
  meeting:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pkgjs/meet@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: 2020-10-09T18:15:11+0000/P1D
        issueTitle: 'bnb Team Meeting <%= date.toFormat("yyyy-MM-dd") %>'
